env:
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  TERM: xterm #Needed for dotnet to output ANSI SGR colour codes
name: Build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      #Setup
      - name: Check out repository
        uses: actions/checkout@v6
      #- name: Set up .NET SDK
        #uses: actions/setup-dotnet@v5
        #with: {dotnet-version: 10.0}
      - name: Set up Alpine
        uses: jirutka/setup-alpine@v1
        with: {packages: dotnet10-sdk-aot}

      #Build
      #- name: Build
        #run: |
          #dotnet format "./DOOMModLoader/DOOMModLoader.csproj" analyzers --severity info --verify-no-changes
          #dotnet format "./DOOMModLoader/DOOMModLoader.csproj" style --severity info --verify-no-changes

          #echo -e "::group::\e[36;1mLinux Build (Runtime-dependent)\e[0m"
          #dotnet publish "./DOOMModLoader/DOOMModLoader.csproj" --no-self-contained --output "./Build/Linux/" --runtime linux-x64
          #echo "::endgroup::"

          #echo -e "::group::\e[36;1mWindows Build (Runtime-dependent)\e[0m"
          #dotnet publish "./DOOMModLoader/DOOMModLoader.csproj" --no-self-contained --output "./Build/Windows/" --runtime win-x64
          #echo "::endgroup::"

          #echo -e "\e[36;1m$ ./DOOMModLoader -help\e[0m"
          #./Build/Linux/DOOMModLoader -help
      - name: Native build and test
        shell: alpine.sh {0}
        run: |
          dotnet format "./DOOMModLoader/DOOMModLoader.csproj" analyzers --severity info --verify-no-changes
          dotnet format "./DOOMModLoader/DOOMModLoader.csproj" style --severity info --verify-no-changes

          echo -e "::group::\e[36;1mLinux Build (Native)"
          dotnet publish "./DOOMModLoader/DOOMModLoader.csproj" --output "./Build/Linux/" "--property:CustomConditionBuildType=AOTStatic" --runtime linux-musl-x64 --self-contained
          echo "::endgroup::"

          echo -e "\e[36;1m$ ./DOOMModLoader -help\e[0m"
          ./Build/Linux/DOOMModLoader -help

      #Upload
      - name: Display files
        run: find -L "./Build/" -type f -printf "%7s B %p\n" | sort --key=3
      - name: Upload (Linux)
        uses: actions/upload-artifact@v5
        with:
          compression-level: 9
          name: "DOOMModLoader (Linux)"
          path: "./Build/Linux/"
      #- name: Upload (Windows)
        #uses: actions/upload-artifact@v5
        #with:
          #compression-level: 9
          #name: "DOOMModLoader (Windows)"
          #path: "./Build/Windows/"

  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      #Setup
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v5
        with: {dotnet-version: 10.0}

      #Build
      - name: Native Windows build and test
        run: |
          dotnet publish "./DOOMModLoader/DOOMModLoader.csproj" --output "./Build/Windows/" "--property:CustomConditionBuildType=AOT" --runtime win-x64 --self-contained

          Start-Process "./Build/Windows/DOOMModLoader.exe" "-help" -NoNewWindow -Wait

      #Upload
      - name: Display files
        run: Get-ChildItem "./Build/" -Recurse -Name -File
      - name: Upload (Windows)
        uses: actions/upload-artifact@v5
        with:
          compression-level: 9
          name: "DOOMModLoader (Windows)"
          path: "./Build/Windows/"
